name: Actions 😎

on: [push, pull_request]



jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Log resources 

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Unity/Evolutionary_Agents_Simulation/Library
          key: Library-${{ hashFiles('Unity/Evolutionary_Agents_Simulation/Assets/**', 'Unity/Evolutionary_Agents_Simulation/Packages/**', 'Unity/Evolutionary_Agents_Simulation/ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
      #    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectPath: Unity/Evolutionary_Agents_Simulation

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
       #   UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: Unity/Evolutionary_Agents_Simulation

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: Unity/Evolutionary_Agents_Simulation/build
